persons:
    curl -s "http://localhost:3030/api/v1/persons?offset=3&limit=5" | json
parties:
    curl -s "http://localhost:3030/api/v1/parties?party_type_id=PERSON" | json
srv:
    cargo run
graphql:
    npx postgraphile -c ofbiz

graphql-db:
    npx postgraphile -c ofbiz --watch
schema-json:
    apollo client:download-schema --endpoint=http://localhost:5000/graphql

login:
    curl http://localhost:8000/login -d '{"email": "user@userland.com", "pw": "1234"}' -H 'Content-Type: application/json'
as-user:
    curl http://localhost:8000/user -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVzZXIiLCJleHAiOjE2MTc4MzEzMTd9.eboCTzQP7Yztt88FYb62pG7S9Z3aumnetsJaBL4gjCpRh0zxN5XV0k8QnFRnpePOqNp5Xf684QXxLmN41SRS8A' -H 'Content-Type: application/json'

