[workspace]
members = [
	"common",
    "entity-seed",
	"cc-types",
	"cc-pipes",
	"cc-data-srv",
	"cc-agent",
	"deles",
	"cc-bridge",
    "contracts/cc_common",
    "entity-seed/meta-gen",
    "entity-seed/meta-cli",
]

[profile.release]
panic = "abort"
lto = true

