[workspace]
members = [
	"common",
    "entity-seed",
	"cc-types",
	"cc-pipes",
	"srv-dele",
    "contracts/cc_common",
    "entity-seed/meta-gen",
    "entity-seed/meta-cli",
]

[profile.release]
panic = "abort"
lto = true

