simple-consumer:
    cargo run --example simple_consumer -- --topics test
simple-producer:
    cargo run --example simple_producer -- --topic test


kafka:
	zookeeper-server-start /usr/local/etc/kafka/zookeeper.properties & kafka-server-start /usr/local/etc/kafka/server.properties

kafka-stop:
	kafka-server-stop
	zookeeper-server-stop
zk-stop:
	zookeeper-server-stop

consumer topic:
    kafka-console-consumer --bootstrap-server {{env_var("HOST_IP")}}:9092 --topic {{topic}}
create-topic topic:
    kafka-topics --create --topic {{topic}} --if-not-exists --zookeeper localhost:2181 --partitions 1 --replication-factor 1

eth:
    ganache-cli -b 3 -m "hamster coin cup brief quote trick stove draft hobby strong caught unable"

bridge:
    cargo run --bin bridge
queues:
	rabbitmqadmin list queues vhost name node messages message_stats.publish_details.rate
listeners:
	rabbitmq-diagnostics -s listeners

