meta:
    cargo run --bin meta-cli
seed:
    cargo run --bin seed
srv:
    cargo run --bin meta_srv

mig:
	diesel migration run
revert:
    diesel migration revert
redo:
    diesel migration redo
gen target:
    diesel migration generate {{target}}

# $ just test select
test target:
    cargo test {{target}} --color=always --package entity-seed --no-fail-fast -- --exact -Z unstable-options --format=json --show-output

resetdb:
    dropdb seed
    createdb seed
    diesel migration run

security:
    cargo run --bin seed all security

all:
    cargo run --bin seed all example
    # cargo run --bin seed all security
    # cargo run --bin seed wrapper security example

# $ just cli data-files
cli cmd:
    cargo run --bin seed {{cmd}}
