version="0.1"
header='''use serde_derive::{Deserialize, Serialize};
// use crate::schema::{{table}};
use crate::schema::*;
use diesel::prelude::*;
'''

enum_header='''#[derive(Debug, PartialEq, Clone, Deserialize, Serialize)]
pub enum EntityTypes {
'''
enum_footer="}"
enum_output="src/models/enum_types.rs"

#seed_types="../cc-types/src/models/{{module}}_types.rs"
#seed_wrapper="../cc-types/src/models/model_types.rs"
seed_types="src/models/{{module}}_types.rs"
seed_wrapper="src/models/model_types.rs"

[api]
gen_root="../cc-types/src"

[security]
up_sql="migrations/2021-03-09-120106_security/up.sql"
down_sql="migrations/2021-03-09-120106_security/down.sql"
model="src/models/security.rs"

[common]
up_sql="migrations/2021-03-09-104216_common/up.sql"
down_sql="migrations/2021-03-09-104216_common/down.sql"
model="src/models/common.rs"

[example]
up_sql="migrations/2021-03-14-132527_example/up.sql"
down_sql="migrations/2021-03-14-132527_example/down.sql"
model="src/models/example.rs"

