version="0.1"

[generate]
sql="migrations/2021-03-09-083808_example/up.sql"
model="src/models/example.rs"
header='''use serde_derive::{Deserialize, Serialize};
use crate::schema::{{table}};
use diesel::prelude::*;
'''

