info:
	python -m bluefin.procs.emitter info
srv:
	python -m bluefin.srv.bluefin_srv
list:
	python -m bluefin.eth.alpha_builder objects

sl file:
	python -m sagas.tool.creators normal {{file}}.py
	streamlit run {{file}}.py


