token:
	cargo run -- token
# ink OrderItem
ink ent:
    cargo run -- entity {{ent}} ink

# Cargo会将自己限制在本地下载的板条箱中，即使索引的本地副本中可能有较新的版本也是如此
install:
	cargo install --path . --offline

info ent:
    cargo run -- meta {{ent}} 
    cargo run -- rels -i -s {{ent}} 

gen-seed:
    cargo run -- convert {{env_var("HOME")}}/ofbiz/applications/datamodel/data/demo/AccountingDemoData.xml
    cargo run -- convert {{env_var("HOME")}}/ofbiz/applications/datamodel/data/demo/ContentDemoData.xml

dirs:
    echo {{env_var("HOME")}}
    echo {{invocation_directory()}}
