token:
	cargo run -- token
# ink OrderItem
ink ent:
    cargo run -- entity {{ent}} ink

# Cargo会将自己限制在本地下载的板条箱中，即使索引的本地副本中可能有较新的版本也是如此
install:
	cargo install --path . --offline

info ent:
    cargo run -- meta {{ent}} 
    cargo run -- rels -i -s {{ent}} 

gen-seed:
    cargo run -- convert {{env_var("HOME")}}/ofbiz/applications/datamodel/data/demo/AccountingDemoData.xml
    cargo run -- convert {{env_var("HOME")}}/ofbiz/applications/datamodel/data/demo/ContentDemoData.xml
    cargo run -- convert {{env_var("HOME")}}/ofbiz/applications/datamodel/data/demo/OrderDemoData.xml
    cargo run -- convert {{env_var("HOME")}}/ofbiz/applications/datamodel/data/demo/WorkEffortDemoData.xml

dirs:
    echo {{env_var("HOME")}}
    echo {{invocation_directory()}}

kafka:
	zookeeper-server-start /usr/local/etc/kafka/zookeeper.properties & kafka-server-start /usr/local/etc/kafka/server.properties

kafka-stop:
	kafka-server-stop 
	zookeeper-server-stop 

consumer:
    kafka-console-consumer --bootstrap-server {{env_var("HOST_IP")}}:9092 --topic measure.entities
create-topic topic:
    kafka-topics --create --topic {{topic}} --if-not-exists --zookeeper localhost:2181 --partitions 1 --replication-factor 1



