CREATE TABLE test_person(
    salutation VARCHAR(100),
    first_name VARCHAR(100),
    middle_name VARCHAR(100),
    last_name VARCHAR(100),
    personal_title VARCHAR(100),
    suffix VARCHAR(100),
    nickname VARCHAR(100),
    first_name_local VARCHAR(100),
    middle_name_local VARCHAR(100),
    last_name_local VARCHAR(100),
    other_local VARCHAR(100),
    member_id BIGINT,
    gender BOOLEAN,
    birth_date DATE,
    deceased_date DATE,
--     height NUMERIC(18,3),
--     weight NUMERIC(18,3),
    mothers_maiden_name VARCHAR(255),
    old_marital_status BOOLEAN,
    marital_status_enum_id BIGINT,
    social_security_number VARCHAR(255),
    passport_number VARCHAR(255),
    passport_expire_date DATE,
--     total_years_work_experience NUMERIC(18,3),
    comments VARCHAR(255),
    employment_status_enum_id BIGINT,
    residence_status_enum_id BIGINT,
    occupation VARCHAR(100),
    years_with_employer BIGINT,
    months_with_employer BIGINT,
    existing_customer BOOLEAN,
    card_id BIGINT,

    party_id BIGSERIAL PRIMARY KEY
);
