use crate::models::security_types::*;
use crate::models::party_types::*;


#[derive(Deserialize, Debug)]
pub struct SeedRecords {
    pub items: Vec<SeedTypes>
}

#[derive(Deserialize, Debug)]
pub enum SeedTypes {
    X509IssuerProvision(X509IssuerProvision),
    UserLogin(UserLogin),
    UserLoginPasswordHistory(UserLoginPasswordHistory),
    UserLoginHistory(UserLoginHistory),
    UserLoginSession(UserLoginSession),
    SecurityGroup(SecurityGroup),
    SecurityGroupPermission(SecurityGroupPermission),
    SecurityPermission(SecurityPermission),
    UserLoginSecurityGroup(UserLoginSecurityGroup),
    ProtectedView(ProtectedView),
    TarpittedLoginView(TarpittedLoginView),
    Addendum(Addendum),
    Agreement(Agreement),
    AgreementAttribute(AgreementAttribute),
    AgreementGeographicalApplic(AgreementGeographicalApplic),
    AgreementItem(AgreementItem),
    AgreementItemAttribute(AgreementItemAttribute),
    AgreementItemType(AgreementItemType),
    AgreementItemTypeAttr(AgreementItemTypeAttr),
    AgreementContent(AgreementContent),
    AgreementContentType(AgreementContentType),
    AgreementPartyApplic(AgreementPartyApplic),
    AgreementProductAppl(AgreementProductAppl),
    AgreementPromoAppl(AgreementPromoAppl),
    AgreementFacilityAppl(AgreementFacilityAppl),
    AgreementRole(AgreementRole),
    AgreementTerm(AgreementTerm),
    AgreementTermAttribute(AgreementTermAttribute),
    AgreementType(AgreementType),
    AgreementTypeAttr(AgreementTypeAttr),
    AgreementWorkEffortApplic(AgreementWorkEffortApplic),
    TermType(TermType),
    TermTypeAttr(TermTypeAttr),
    AgreementEmploymentAppl(AgreementEmploymentAppl),
    CommContentAssocType(CommContentAssocType),
    CommEventContentAssoc(CommEventContentAssoc),
    CommunicationEvent(CommunicationEvent),
    CommunicationEventProduct(CommunicationEventProduct),
    CommunicationEventPrpTyp(CommunicationEventPrpTyp),
    CommunicationEventPurpose(CommunicationEventPurpose),
    CommunicationEventRole(CommunicationEventRole),
    CommunicationEventType(CommunicationEventType),
    ContactMech(ContactMech),
    ContactMechAttribute(ContactMechAttribute),
    ContactMechLink(ContactMechLink),
    ContactMechPurposeType(ContactMechPurposeType),
    ContactMechType(ContactMechType),
    ContactMechTypeAttr(ContactMechTypeAttr),
    ContactMechTypePurpose(ContactMechTypePurpose),
    EmailAddressVerification(EmailAddressVerification),
    PartyContactMech(PartyContactMech),
    PartyContactMechPurpose(PartyContactMechPurpose),
    PostalAddress(PostalAddress),
    PostalAddressBoundary(PostalAddressBoundary),
    TelecomNumber(TelecomNumber),
    FtpAddress(FtpAddress),
    ValidContactMechRole(ValidContactMechRole),
    NeedType(NeedType),
    PartyNeed(PartyNeed),
    AddressMatchMap(AddressMatchMap),
    Affiliate(Affiliate),
    Party(Party),
    PartyIdentification(PartyIdentification),
    PartyIdentificationType(PartyIdentificationType),
    PartyGeoPoint(PartyGeoPoint),
    PartyAttribute(PartyAttribute),
    PartyCarrierAccount(PartyCarrierAccount),
    PartyClassification(PartyClassification),
    PartyClassificationGroup(PartyClassificationGroup),
    PartyClassificationType(PartyClassificationType),
    PartyContent(PartyContent),
    PartyContentType(PartyContentType),
    PartyDataSource(PartyDataSource),
    PartyGroup(PartyGroup),
    PartyIcsAvsOverride(PartyIcsAvsOverride),
    PartyInvitation(PartyInvitation),
    PartyInvitationGroupAssoc(PartyInvitationGroupAssoc),
    PartyInvitationRoleAssoc(PartyInvitationRoleAssoc),
    PartyNameHistory(PartyNameHistory),
    PartyNote(PartyNote),
    PartyProfileDefault(PartyProfileDefault),
    PartyRelationship(PartyRelationship),
    PartyRelationshipType(PartyRelationshipType),
    PartyRole(PartyRole),
    PartyStatus(PartyStatus),
    PartyType(PartyType),
    PartyTypeAttr(PartyTypeAttr),
    Person(Person),
    PriorityType(PriorityType),
    RoleType(RoleType),
    RoleTypeAttr(RoleTypeAttr),
    Vendor(Vendor),
}

